image: "python:3.7"

before_script:
  - python --version

#  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
#    -O miniconda.sh
#  - bash miniconda.sh -b -p $HOME/miniconda
#  - export PATH="$HOME/miniconda/bin:$PATH"
#  - conda update --yes conda
#  - conda config --add channels conda-forge  -
  - pip install -U cython setuptools pip numpy
  - pip install -r requirements.txt

stages:
  - Test

pytest:
  stage: Test
  script:
  - pytest --cov dj_schemas --cov-report html --cov-report xml:coverage.xml
  - coverage report -m
  - coverage-badge
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'


#nosetest:
#  stage: Test
#  script:
#  - nosetests --with-coverage --cover-erase --cover-package=tests/ --cover-html
#  coverage: '/Code coverage: \d+\.\d+/'

#prettycoverage:
#  stage: Test
#  script:
##    - npm install
#    - npx nyc --reporter cobertura mocha
#  artifacts:
#    reports:
#      cobertura: coverage/cobertura-coverage.xml
