language: python
python:
    - '3.7'
notifications:
  email: false
before_install:
 - python --version
 - pip install -U cython setuptools pip numpy
# - git clone https://gitlab.com/mmyros/public_spikesorting_datasets.git ~/public_spikesorting_datasets # Extra test data

install:
  - pip install -r requirements.txt
  - pip install --editable .
  - pip install pytest-cov
  - pip install coveralls
  - pip install codecov
script: pytest --cov=cluster_quality tests/
after_success:
  - codecov
  - coveralls
