image: "python:3.7"

before_install:
  - python --version
  - pip install -U cython setuptools pip numpy
  - pip install -r requirements.txt

stages:
  - Test

pytest:
  stage: Test
  language: python
  script:
  - pytest --cov dj_schemas --cov-report html --cov-report xml:coverage.xml
  - coverage report -m
  - coverage-badge
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'


#nosetest:
#  stage: Test
#  script:
#  - nosetests --with-coverage --cover-erase --cover-package=tests/ --cover-html
#  coverage: '/Code coverage: \d+\.\d+/'

#prettycoverage:
#  stage: Test
#  script:
##    - npm install
#    - npx nyc --reporter cobertura mocha
#  artifacts:
#    reports:
#      cobertura: coverage/cobertura-coverage.xml
